Repository SciTools/iris-esmf-regrid, pull requests merged in 2020-11, with the labels that each got.

#5 Add first test
  esmf_regrid/tests/__init__.py
  esmf_regrid/tests/results/test_GridInfo/small_grid.txt
  esmf_regrid/tests/test_GridInfo.py
  noxfile.py
Labels: New: Pull Request, Type: Testing

#7 add badges
  README.md
Labels: New: Pull Request, Type: Infrastructure

#9 pytest and codecov
  .cirrus.yml
  .flake8
  esmf_regrid/tests/__init__.py
  esmf_regrid/tests/results/unit/esmf_regridder/test_GridInfo/small_grid.txt
  esmf_regrid/tests/unit/__init__.py
  esmf_regrid/tests/unit/esmf_regridder/test_GridInfo.py
  noxfile.py
  pyproject.toml
  setup.cfg
Labels: New: Pull Request, Type: Infrastructure, Type: Testing

#8 add cache refresh
  .cirrus.yml
Labels: New: Pull Request, Type: Infrastructure

#6 Update issue templates
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---custom-issue.md
  .github/ISSUE_TEMPLATE/--feature-request.md
Labels: New: Pull Request, Type: Infrastructure

#10 add codecov badge
  README.md
Labels: New: Pull Request, Type: Infrastructure

#11 rename github template files
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/custom-issue.md
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: New: Pull Request, Type: Infrastructure

#14 check nox conda requirements
  noxfile.py
Labels: New: Pull Request, Type: Enhancement

#12 Create stale.yml
  .github/workflows/stale.yml
Labels: New: Pull Request, Type: Infrastructure

#13 Create greetings.yml
  greetings.yml
Labels: New: Pull Request, Type: Infrastructure

#15 use nox session.bin
  noxfile.py
Labels: New: Pull Request, Type: Enhancement

#16 Update stale.yml
  .github/workflows/stale.yml
Labels: New: Pull Request, Type: Enhancement

#18 remove greeting.yml
  greetings.yml
Labels: New: Pull Request

#17 Create greetings.yml
  .github/workflows/greetings.yml
Labels: New: Pull Request

#19 Update README.md
  README.md
Labels: New: Pull Request
